# Generated by Django 3.0.3 on 2020-03-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='destination_number',
            field=models.IntegerField(default=846654),
            preserve_default=False,
        ),
    ]
